# Binary Sensors
# Work Computer

# IOTLink
- platform: mqtt
  name: "WC - Connected"
  state_topic: "iotlink/pi/jdh-pc/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1

- platform: mqtt
  name: "WC - Charging"
  state_topic: "iotlink/pi/jdh-pc/windows-monitor/stats/power/status"
  value_template: "{{ value }}"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: "plug"
  availability_topic: "iotlink/pi/jdh-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "WC - Battery Status"
  state_topic: "iotlink/pi/jdh-pc/windows-monitor/stats/battery/status"
  value_template: "{{ value }}"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: "plug"
  availability_topic: "iotlink/pi/jdh-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
