# Binary Sensors
# Personal Computer

# IOTLink
- platform: mqtt
  name: "PC - Connected"
  state_topic: "iotlink/workgroup/jesse-pc/lwt"
  value_template: "{{ value }}"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "connectivity"
  qos: 1

- platform: mqtt
  name: "PC - Charging"
  state_topic: "iotlink/workgroup/jesse-pc/windows-monitor/stats/power/status"
  value_template: "{{ value }}"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: "plug"
  availability_topic: "iotlink/workgroup/jesse-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "PC - Battery Status"
  state_topic: "iotlink/workgroup/jesse-pc/windows-monitor/stats/battery/status"
  value_template: "{{ value }}"
  payload_on: "Online"
  payload_off: "Offline"
  device_class: "plug"
  availability_topic: "iotlink/workgroup/jesse-pc/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
