- platform: generic_thermostat
  unique_id: climate.roomtemp
  name: Thermostat
  heater: switch.heater
  target_sensor: sensor.hue_motion_sensor_1_temperature
  min_temp: 10
  max_temp: 30
  target_temp: 20.5
  cold_tolerance: 0
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  initial_hvac_mode: "off"
  #away_temp: 16
  precision: 0.5
