- platform: generic_thermostat
  unique_id: climate.roomtemp
  name: Thermostat
  heater: switch.heater
  target_sensor: sensor.bedroom_motion_sensor_temperature
  min_temp: 10
  max_temp: 30
  target_temp: 20.5
  cold_tolerance: 0
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  initial_hvac_mode: "off"
  # away_temp: input_number.climate_temperature_night
  precision: 0.5
