homeassistant:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  unit_system: metric
  time_zone: Australia/Melbourne

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

wake_on_lan:

# Text to speech
tts:
  - platform: google_translate

# Spotify
spotify: !include spotify.yaml

frontend:
  themes: !include_dir_merge_named themes

# Base stuff
automation: !include automations.yaml
group: !include groups.yaml
scene: !include scenes.yaml
script: !include_dir_merge_named scripts/

# Custom stuff
binary_sensor: !include_dir_merge_named binary_sensor/
camera: !include_dir_merge_named camera/
climate: !include climate.yaml
device_tracker: !include device_tracker.yaml
sensor: !include_dir_merge_named sensor/
switch: !include_dir_merge_named switch/
