# Switches
# Personal Computer

- platform: template
  switches:
    pc:
      friendly_name: "Personal Computer"
      value_template: "{{ is_state('binary_sensor.pc_connected', 'on') }}"
      turn_on:
        service: script.pc_wake
      turn_off:
        service: script.pc_suspend
      icon_template: mdi:laptop
