# Sensors
# Wall Tablet

# IOTLink
- platform: mqtt
  name: "Tablet - Current User"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/system/current-user"
  unit_of_measurement: ""
  icon: mdi:account
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - Idle Time"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/system/idle-time"
  unit_of_measurement: "seconds"
  icon: mdi:timer
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - CPU Usage"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/cpu/usage"
  unit_of_measurement: "%"
  icon: mdi:speedometer
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - RAM Usage"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/memory/usage"
  unit_of_measurement: "%"
  icon: mdi:memory
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - RAM Available"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/memory/available"
  unit_of_measurement: "MB"
  icon: mdi:memory
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - RAM Used"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/memory/used"
  unit_of_measurement: "MB"
  icon: mdi:memory
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - RAM Total"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/memory/total"
  unit_of_measurement: "MB"
  icon: mdi:memory
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - Remaining Battery"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/battery/remaining-percent"
  unit_of_measurement: "%"
  device_class: battery
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - Remaining Battery Time"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/battery/remaining-time"
  unit_of_measurement: "minutes"
  icon: mdi:timer
  value_template: "{{ ( value | float / 60 ) | int }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - Predicted Lifetime"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/battery/full-lifetime"
  unit_of_measurement: "minutes"
  icon: mdi:timer
  value_template: "{{ ( value | float / 60 ) | int }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - HDD Usage (C)"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/hard-drive/c/drive-usage"
  unit_of_measurement: "%"
  icon: mdi:chart-donut
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - HDD Total Size (C)"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/hard-drive/c/total-size"
  unit_of_measurement: "GB"
  icon: mdi:harddisk
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - HDD Total Free Space (C)"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/hard-drive/c/total-free-space"
  unit_of_measurement: "GB"
  icon: mdi:harddisk
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - HDD Free Space (C)"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/hard-drive/c/available-free-space"
  unit_of_measurement: "GB"
  icon: mdi:harddisk
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - HDD Used Space (C)"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/hard-drive/c/used-space"
  unit_of_measurement: "GB"
  icon: mdi:harddisk
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - HDD Format (C)"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/hard-drive/c/drive-format"
  unit_of_measurement: ""
  icon: mdi:harddisk
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - HDD Label (C)"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/hard-drive/c/volume-label"
  unit_of_measurement: ""
  icon: mdi:harddisk
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - Network IPv4"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/network/0/ipv4"
  unit_of_measurement: ""
  icon: mdi:lan
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - Network IPv6"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/network/0/ipv6"
  unit_of_measurement: ""
  icon: mdi:lan
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - Network Speed"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/network/0/speed"
  unit_of_measurement: "Mbps"
  icon: mdi:speedometer
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1

- platform: mqtt
  name: "Tablet - Network Wired"
  state_topic: "iotlink/workgroup/jesse-tablet/windows-monitor/stats/network/0/wired"
  unit_of_measurement: ""
  icon: mdi:ethernet
  value_template: "{{ value }}"
  availability_topic: "iotlink/workgroup/jesse-tablet/lwt"
  payload_available: "ON"
  payload_not_available: "OFF"
  qos: 1
